language: python
python:
  - 3.8
install:
  - pip install -q pipenv codecov
  - pipenv sync --dev
script:
  - flake8 primoj/funcoes.py
  - python -m pytest -v --cov=primoj

after_success:
  - codecov
